# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_groupinfo_person_question_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='groups',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
