# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userinfo_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='permission',
            field=models.CharField(max_length=800),
        ),
    ]
