# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170207_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
