# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='permission',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='permission',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
