# Form implementation generated from reading ui file 'd:\code\study\python\test\test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1305, 476)
        self.SelectSrcFile = QtWidgets.QPushButton(parent=Dialog)
        self.SelectSrcFile.setGeometry(QtCore.QRect(40, 340, 93, 28))
        self.SelectSrcFile.setObjectName("SelectSrcFile")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 90, 291, 16))
        self.label.setObjectName("label")
        self.SourceTable = QtWidgets.QTableView(parent=Dialog)
        self.SourceTable.setGeometry(QtCore.QRect(40, 110, 681, 192))
        self.SourceTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.SourceTable.setObjectName("SourceTable")
        self.ChooseDestDir = QtWidgets.QPushButton(parent=Dialog)
        self.ChooseDestDir.setGeometry(QtCore.QRect(780, 110, 151, 28))
        self.ChooseDestDir.setObjectName("ChooseDestDir")
        self.DestFileName = QtWidgets.QLineEdit(parent=Dialog)
        self.DestFileName.setGeometry(QtCore.QRect(890, 190, 113, 21))
        self.DestFileName.setObjectName("DestFileName")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(780, 150, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(780, 190, 111, 16))
        self.label_3.setObjectName("label_3")
        self.DestFileDir = QtWidgets.QLineEdit(parent=Dialog)
        self.DestFileDir.setGeometry(QtCore.QRect(890, 150, 381, 21))
        self.DestFileDir.setObjectName("DestFileDir")
        self.StartGenerate = QtWidgets.QPushButton(parent=Dialog)
        self.StartGenerate.setGeometry(QtCore.QRect(570, 340, 93, 28))
        self.StartGenerate.setObjectName("StartGenerate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SelectSrcFile.setText(_translate("Dialog", "选择源文件"))
        self.label.setText(_translate("Dialog", "源文件 以及相关sheet,行列信息"))
        self.ChooseDestDir.setText(_translate("Dialog", "选择目标文件路径"))
        self.label_2.setText(_translate("Dialog", "目标文件目录: "))
        self.label_3.setText(_translate("Dialog", "目标文件名: "))
        self.StartGenerate.setText(_translate("Dialog", "开始生成"))
