# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\github\study\PyQt5\DownLoadData\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 927)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 441, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datasource_label = QtWidgets.QLabel(self.layoutWidget)
        self.datasource_label.setObjectName("datasource_label")
        self.horizontalLayout.addWidget(self.datasource_label)
        self.datasource_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.datasource_comboBox.setObjectName("datasource_comboBox")
        self.horizontalLayout.addWidget(self.datasource_comboBox)
        self.startDownloadData_button = QtWidgets.QPushButton(self.layoutWidget)
        self.startDownloadData_button.setObjectName("startDownloadData_button")
        self.horizontalLayout.addWidget(self.startDownloadData_button)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.announcement_label = QtWidgets.QLabel(self.centralWidget)
        self.announcement_label.setObjectName("announcement_label")
        self.horizontalLayout_4.addWidget(self.announcement_label)
        self.updateAnnouncement_button = QtWidgets.QPushButton(self.centralWidget)
        self.updateAnnouncement_button.setObjectName("updateAnnouncement_button")
        self.horizontalLayout_4.addWidget(self.updateAnnouncement_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.announcement_dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.announcement_dateEdit.setObjectName("announcement_dateEdit")
        self.horizontalLayout_5.addWidget(self.announcement_dateEdit)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.isClearAnnDatabase_comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.isClearAnnDatabase_comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.isClearAnnDatabase_comboBox.setObjectName("isClearAnnDatabase_comboBox")
        self.horizontalLayout_5.addWidget(self.isClearAnnDatabase_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.announcement_tableView = QtWidgets.QTableView(self.centralWidget)
        self.announcement_tableView.setObjectName("announcement_tableView")
        self.verticalLayout_2.addWidget(self.announcement_tableView)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.weightData_label = QtWidgets.QLabel(self.centralWidget)
        self.weightData_label.setObjectName("weightData_label")
        self.horizontalLayout_6.addWidget(self.weightData_label)
        self.updateWeightData_button = QtWidgets.QPushButton(self.centralWidget)
        self.updateWeightData_button.setObjectName("updateWeightData_button")
        self.horizontalLayout_6.addWidget(self.updateWeightData_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.weight_dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.weight_dateEdit.setObjectName("weight_dateEdit")
        self.horizontalLayout_7.addWidget(self.weight_dateEdit)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.isClearWeightDatabase_comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.isClearWeightDatabase_comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.isClearWeightDatabase_comboBox.setObjectName("isClearWeightDatabase_comboBox")
        self.horizontalLayout_7.addWidget(self.isClearWeightDatabase_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.weightData_tableView = QtWidgets.QTableView(self.centralWidget)
        self.weightData_tableView.setObjectName("weightData_tableView")
        self.verticalLayout_3.addWidget(self.weightData_tableView)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.errorInfo_label = QtWidgets.QLabel(self.centralWidget)
        self.errorInfo_label.setObjectName("errorInfo_label")
        self.gridLayout_5.addWidget(self.errorInfo_label, 0, 0, 1, 1)
        self.errorInfo_tableView = QtWidgets.QTableView(self.centralWidget)
        self.errorInfo_tableView.setObjectName("errorInfo_tableView")
        self.gridLayout_5.addWidget(self.errorInfo_tableView, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 2, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.marketData_label = QtWidgets.QLabel(self.centralWidget)
        self.marketData_label.setObjectName("marketData_label")
        self.horizontalLayout_2.addWidget(self.marketData_label)
        self.updateHistMarketData_button_ = QtWidgets.QPushButton(self.centralWidget)
        self.updateHistMarketData_button_.setObjectName("updateHistMarketData_button_")
        self.horizontalLayout_2.addWidget(self.updateHistMarketData_button_)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.marketdata_sttarttime_label = QtWidgets.QLabel(self.centralWidget)
        self.marketdata_sttarttime_label.setObjectName("marketdata_sttarttime_label")
        self.horizontalLayout_3.addWidget(self.marketdata_sttarttime_label)
        self.marketdata_starttime_edit = QtWidgets.QDateEdit(self.centralWidget)
        self.marketdata_starttime_edit.setObjectName("marketdata_starttime_edit")
        self.horizontalLayout_3.addWidget(self.marketdata_starttime_edit)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.isClearHistMarketDatabase_comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.isClearHistMarketDatabase_comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.isClearHistMarketDatabase_comboBox.setObjectName("isClearHistMarketDatabase_comboBox")
        self.horizontalLayout_3.addWidget(self.isClearHistMarketDatabase_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.marketData_tableView = QtWidgets.QTableView(self.centralWidget)
        self.marketData_tableView.setObjectName("marketData_tableView")
        self.verticalLayout.addWidget(self.marketData_tableView)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)
        self.groupBox.raise_()
        self.announcement_label.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.datasource_label.setText(_translate("MainWindow", "选择数据库:"))
        self.startDownloadData_button.setText(_translate("MainWindow", "更新所有数据"))
        self.announcement_label.setText(_translate("MainWindow", "公告数据:"))
        self.updateAnnouncement_button.setText(_translate("MainWindow", "开始更新数据"))
        self.label_5.setText(_translate("MainWindow", "起始时间:"))
        self.label.setText(_translate("MainWindow", "是否清空数据库:"))
        self.weightData_label.setText(_translate("MainWindow", "权重与行业分类数据: "))
        self.updateWeightData_button.setText(_translate("MainWindow", "开始更新数据"))
        self.label_6.setText(_translate("MainWindow", "起始时间:"))
        self.label_3.setText(_translate("MainWindow", "是否清空数据库:"))
        self.errorInfo_label.setText(_translate("MainWindow", "错误提示信息: "))
        self.marketData_label.setText(_translate("MainWindow", "历史行情数据:"))
        self.updateHistMarketData_button_.setText(_translate("MainWindow", "开始更新数据"))
        self.marketdata_sttarttime_label.setText(_translate("MainWindow", "起始时间:"))
        self.label_2.setText(_translate("MainWindow", "是否清空数据库:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

