# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('scale', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
